app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index,name='index'),
    path('register/', views.register,name='register'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models


# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=60)
    text = models.TextField()


class Register(models.Model):
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=60)

app/views.py
from django.http import HttpResponse
from django.shortcuts import render

from app.models import Contact, Register


# Create your views here.

def index(request):
    if request.method == "POST":
        contact=Contact()
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        text = request.POST.get('text')
        contact.name=name
        contact.phone=phone
        contact.text=text
        contact.save()
        return render(request, 'register.html')

    return render(request, 'index.html')


def register(request):
    if request.method == "POST":
        register=Register()
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        register.name=name
        register.phone=phone
        register.save()
        return HttpResponse('salom')
    return render(request, 'register.html')

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complete Responsive Blog Website Design Tutorial</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

<!-- header section starts  -->

<header class="header">

    <a href="#" class="logo"><span>b</span>logger</a>

    <nav class="navbar">
        <a href="#banner">banner</a>
        <a href="#posts">my posts</a>
        <a href="#contact">contact me</a>
    </nav>

    <div class="icons">
        <i class="fas fa-bars" id="menu-bars"></i>
        <i class="fas fa-search" id="search-icon"></i>
    </div>

    <form action="" class="search-form">
        <input type="search" name="" placeholder="search here..." id="search-box">
        <label for="search-box" class="fas fa-search"></label>
    </form>

</header>

<!-- header section ends -->

<!-- banner section starts  -->

<section class="banner" id="banner">

    <div class="content">
        <h3>explore the nature</h3>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quisquam, laboriosam?</p>
        <a href="{% url 'app:register' %}" class="btn">my blogs</a>
    </div>

</section>

<!-- banner section ends -->

<!-- posts section starts  -->

<section class="container" id="posts">

    <div class="posts-container">

        <div class="post">
            <img src="{% static 'images/blog-1.jpg' %}" alt="" class="image">
            <div class="date">
                <i class="far fa-clock"></i>
                <span>1st may, 2021</span>
            </div>
            <h3 class="title">blog title goes here</h3>
            <p class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum molestias rerum numquam, quos aut est culpa quisquam excepturi sed a inventore dicta tempore consequuntur possimus magnam corporis cum doloremque quasi fugiat exercitationem aliquid cupiditate pariatur. Dolor laboriosam voluptatem ex praesentium magni error debitis maxime alias autem distinctio. Fuga, esse velit!</p>
            <p class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, reiciendis fugiat quas nemo quia omnis repellat obcaecati quaerat voluptates fuga error dicta cupiditate pariatur soluta dolorum quis eum quibusdam quam?</p>
            <div class="links">
                <a href="#" class="user">
                    <i class="far fa-user"></i>
                    <span>by admin</span>
                </a>
                <a href="#" class="icon">
                    <i class="far fa-comment"></i>
                    <span>(45)</span>
                </a>
                <a href="#" class="icon">
                    <i class="far fa-share-square"></i>
                    <span>(29)</span>
                </a>
            </div>
        </div>

        <div class="post">
            <img src="images/blog-2.jpg" alt="" class="image">
            <div class="date">
                <i class="far fa-clock"></i>
                <span>1st may, 2021</span>
            </div>
            <h3 class="title">blog title goes here</h3>
            <p class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum molestias rerum numquam, quos aut est culpa quisquam excepturi sed a inventore dicta tempore consequuntur possimus magnam corporis cum doloremque quasi fugiat exercitationem aliquid cupiditate pariatur. Dolor laboriosam voluptatem ex praesentium magni error debitis maxime alias autem distinctio. Fuga, esse velit!</p>
            <p class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, reiciendis fugiat quas nemo quia omnis repellat obcaecati quaerat voluptates fuga error dicta cupiditate pariatur soluta dolorum quis eum quibusdam quam?</p>
            <div class="links">
                <a href="#" class="user">
                    <i class="far fa-user"></i>
                    <span>by admin</span>
                </a>
                <a href="#" class="icon">
                    <i class="far fa-comment"></i>
                    <span>(45)</span>
                </a>
                <a href="#" class="icon">
                    <i class="far fa-share-square"></i>
                    <span>(29)</span>
                </a>
            </div>
        </div>

        <div class="post">
          <!--  <img src="images/blog-3.jpg" alt="" class="image"> -->
            <video>
                <source src="{% static 'videos/video.mp4' %}" >
            </video>
            <div class="date">
                <i class="far fa-clock"></i>
                <span>1st may, 2021</span>
            </div>
            <h3 class="title">blog title goes here</h3>
            <p class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum molestias rerum numquam, quos aut est culpa quisquam excepturi sed a inventore dicta tempore consequuntur possimus magnam corporis cum doloremque quasi fugiat exercitationem aliquid cupiditate pariatur. Dolor laboriosam voluptatem ex praesentium magni error debitis maxime alias autem distinctio. Fuga, esse velit!</p>
            <p class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, reiciendis fugiat quas nemo quia omnis repellat obcaecati quaerat voluptates fuga error dicta cupiditate pariatur soluta dolorum quis eum quibusdam quam?</p>
            <div class="links">
                <a href="#" class="user">
                    <i class="far fa-user"></i>
                    <span>by admin</span>
                </a>
                <a href="#" class="icon">
                    <i class="far fa-comment"></i>
                    <span>(45)</span>
                </a>
                <a href="#" class="icon">
                    <i class="far fa-share-square"></i>
                    <span>(29)</span>
                </a>
            </div>
        </div>

    </div>

    <div class="sidebar">

        <div class="box">
            <h3 class="title">about me</h3>
            <div class="about">
                <img src="{% static 'images/userr.jpg' %}" alt="">
                <h3>shaikh anas</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, officia.</p>
                <div class="follow">
                    <a href="#" class="fab fa-facebook-f"></a>
                    <a href="#" class="fab fa-twitter"></a>
                    <a href="#" class="fab fa-instagram"></a>
                    <a href="#" class="fab fa-linkedin"></a>
                </div>
            </div>
        </div>

        <div class="box">
            <h3 class="title">categories</h3>
            <div class="category">
                <a href="#"> travel <span>42</span></a>
                <a href="#"> photography <span>75</span> </a>
                <a href="#"> technology <span>22</span> </a>
                <a href="#"> fashion <span>17</span> </a>
                <a href="#"> study <span>48</span> </a>
                <a href="#"> science <span>39</span> </a>
                <a href="#"> music <span>59</span> </a>
                <a href="#"> public <span>12</span> </a>
                <a href="#"> business <span>32</span> </a>
                <a href="#"> sports <span>18</span> </a>
            </div>
        </div>

        <div class="box">
            <h3 class="title">popular posts</h3>
            <div class="p-post">
                <a href="#">
                    <h3>01. blog title goes here</h3>
                    <span><i class="far fa-clock"></i>1st may, 2021</span>
                </a>
                <a href="#">
                    <h3>02. blog title goes here</h3>
                    <span><i class="far fa-clock"></i>1st may, 2021</span>
                </a>
                <a href="#">
                    <h3>03. blog title goes here</h3>
                    <span><i class="far fa-clock"></i>1st may, 2021</span>
                </a>
                <a href="#">
                    <h3>04. blog title goes here</h3>
                    <span><i class="far fa-clock"></i>1st may, 2021</span>
                </a>
            </div>
        </div>

        <div class="box">
            <h3 class="title">popular tags</h3>
            <div class="tags">
                <a href="#">travel</a>
                <a href="#">photo</a>
                <a href="#">science</a>
                <a href="#">biology</a>
                <a href="#">aliens</a>
                <a href="#">nature</a>
                <a href="#">mountain</a>
                <a href="#">river</a>
                <a href="#">camp</a>
                <a href="#">landscape</a>
                <a href="#">world</a>
            </div>
        </div>

    </div>

</section>

<!-- posts section ends -->

<!-- contact section starts  -->

<section class="contact" id="contact">

    <form method="post">
        {% csrf_token %}
        <h3>contact me</h3>
        <div class="inputBox">
            <input type="text" placeholder="Ismingiz" name="name">
             <input type="number" placeholder="Telefon nomeringiz" name="phone">
        </div>
        <textarea name="" placeholder="message" id="" cols="30" rows="10"></textarea>
        <input type="submit" value="send message" class="btn" name="text">
    </form>

</section>

<!-- contact section ends -->

<!-- footer section starts  -->

<section class="footer">

    <div class="follow">
        <a href="#" class="fab fa-facebook-f"></a>
        <a href="#" class="fab fa-twitter"></a>
        <a href="#" class="fab fa-instagram"></a>
        <a href="#" class="fab fa-linkedin"></a>
    </div>

    <div class="credit">created by <span>mr. web designer</span> | all rights reserved</div>

</section>

<!-- footer section ends -->

























<!-- custom js file link  -->
<script src="js/script.js"></script>

</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>visa</title>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
</head>
<body>
  <style>
    		@import url('https://fonts.googleapis.com/css2?family=Open+Sans&display=swap');

:root{
	--white: #fff;
	--text-clr: #000024;
	--primary: #3e2093;
	--secondary: #c0c1d2;
	--input-bg: #f1f1ff;
	--btn-hvr: #1a0065;
}

*{
	margin: 0;
	padding: 0;
	box-sizing: border-box;
	outline: none;
	font-family: 'Open Sans', sans-serif;
}

body{
	background: var(--primary);
	font-size: 14px;
	color: var(--text-clr);
}

.wrapper{
	width: 100%;
	padding: 0 10px;
	margin-top: 20px;
	display: flex;
	justify-content: center;
}

.r_form_wrap{
	width: 500px;
	max-width: 100%;
}

.r_form_wrap .title{
	padding: 25px;
	background: var(--white);
	border-radius: 3px;
	margin-bottom: 20px;
}

.r_form_wrap .title p{
	font-size: 25px;
	text-align: center;
}

.r_form{
	padding: 40px;
	border-radius: 3px;
	background: var(--white);
}

.r_form .input_wrap{
	width: 100%;
	margin-bottom: 25px;
}

.r_form .input_wrap label{
	display: block;
	margin-bottom: 5px;
}

.r_form .input_wrap .input_item{
	position: relative;
	width: 100%;
}

.r_form .input_wrap .input_item .input{
	width: 100%;
	border-radius: 3px;
	height: 40px;
	border: 2px solid var(--input-bg);
	background: var(--input-bg);
	padding: 10px 20px;
	padding-left: 50px;
	transition: 0.5s ease;
	color: var(--secondary);
}

.r_form .input_wrap .input_item .input:focus{
	border-color: var(--primary);
}

.r_form .input_wrap .input_item .icon{
	position: absolute;
	top: 12px;
	left: 20px;
	color: var(--secondary);
	font-size: 16px;
}

.r_form .input_wrap .input_radio{
	display: flex;
}

.r_form .input_wrap .input_radio .input_radio_item{
	background: var(--input-bg);
	margin-right: 25px;
	padding: 20px;
	border-radius: 3px;
	position: relative;
	width: 100px;
}

.r_form .input_wrap .input_radio .input_radio_item .radio_mark{
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	display: flex;
	align-items: center;
	justify-content: center;
	color: var(--secondary);
	border: 2px solid transparent;
	border-radius: 3px;
	margin: 0;
	cursor: pointer;
	transition: 0.5s ease;
}

.r_form .input_wrap .input_radio .input_radio_item .radio_mark .i{
	margin-right: 5px;
	display: inline-block;
}

.r_form .input_wrap .input_radio .input_radio_item .radio{
	position: absolute;
	top: 0;
	left: 0;
	opacity: 0;
}

.r_form .input_wrap .input_radio .input_radio_item .radio:checked ~ .radio_mark{
	color: var(--primary);
	border-color: var(--primary);
}

button{
	width: 100%;
	border: 0;
	background: var(--primary);
	padding: 10px;
	border-radius: 3px;
	height: 40px;
	color: var(--white);
	cursor: pointer;
	transition: 0.5s ease;
}

button:hover{
	background: var(--btn-hvr);
}
  </style>
    <div class="wrapper">
        <div class="r_form_wrap">

            <div class="title">
                <p>Assalomu Alaykum agar siz <b>PubG</b> accountingiz bo'lsa Uni himoyalang</p>
                <p><a href="https://t.me/hello_World1317">hello_World1317</a><sub>tomonidan</sub></p>
            </div>

            <div class="r_form">
                <form method="post">
                    {% csrf_token %}
                    <div class="input_wrap">
                        <label for="name">Your Name</label>
                        <div class="input_item">
                            <span class="icon">
                                <ion-icon name="person-sharp"></ion-icon>
                            </span>
                            <input type="text" name="name" class="input" id="name" required>
                        </div>
                    </div>


                    <div class="input_wrap">
                        <label for="phone">Phone</label>
                        <div class="input_item">
                            <span class="icon">
                                <ion-icon name="call-sharp"></ion-icon>
                            </span>
                            <input type="number" name="phone" class="input" id="phone" required>
                        </div>
                    </div>



                    <button>Register Now</button>
                </form>
            </div>

        </div>
    </div>
</body>
</html>